{
    "name": "Equipment Rental & Maintenance",
    "version": "19.0.1.0.0",
    "category": "Sales/Rental",
    "summary": "Manage equipment rentals, availability, and maintenance",
    "author": "Mohammed Galal",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "maintenance",
        "sale_management",
        "account",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/rental_product_data.xml",
        "data/rental_sequence.xml",
        "data/rental_cron.xml",
        "views/maintenance_equipment_views.xml",
        "views/rental_order_views.xml",
        "views/equipment_maintenance_views.xml",
        "views/res_config_settings_views.xml",
        "views/rental_availability_views.xml",
        "views/rental_menus.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
}
